### PR TITLE
Add topic details for legal requirements for accessibility

### PR DESCRIPTION
**Pull request by gp23abj**
- Resolved conflicts
- Added "The Legal Aspect of Accessibility" topic
- Added learningMaterial functionality
- Bug fixes and code cleanup

### CODE REVIEW

**Review by cl24abg — DISMISSED** [review]
Happy with the changes made!

**Review by cl24abg — COMMENTED** [review]
Is there a reason you use relative paths in .html but explicit in .js? Just curious!

**Review by cl24abg — APPROVED** [review]
Changes look good to me!

## Generative AI Contribution Statement

1. **Scope of AI Assistance**:
   - [] Code generation 
   - [x] Testing
   - [] Other
   - [] Not Used

2. **Rationale for AI Use**:
   - Used to help with code understanding and as a tool for QA.

**Comment by gp23abj** [comment]
> Is there a reason you use relative paths in .html but explicit in .js? Just curious!

Can you show me exactly what you mean?

Sometimes you cannot use relative paths and sometimes you shouldn't, but if there are real inconsistencies we should fix that.

**Comment by cl24abg** [comment]
It just noticed it in the rollback pages file structure commit (https://github.com/rt2-group4/UOH-AWA/pull/11/commits/7b2b9a61dc11f351d21d6709183d4e29cb98e94c)

**Pull request merged**
